[[main]]
none = "none"


# [[main]]
# name = "Contatti"
# url = "/contatti/"
# # pre = "newspaper"
# pageRef = "contacts"
# identifier = "370333fzPk"
# weight = 5

[[main]]
name = "Articoli"
url = "/articles/"
# pre = "newspaper"
pageRef = "atricles"
identifier = "3703knfzPk"
weight = 10

# [[main]]
# name = "Etichette"
# # pre = "tags"
# pageRef = "tags"
# identifier = "Tj5XqIBEPW"
# weight = 20

# [[main]]
# name = "Autori"
# # pre = "users"
# pageRef = "authors"
# identifier = "Tj5GqJREPW"
# weight = 30

# # [[main]]
# # name = "Serie"
# # # pre = "book"
# # pageRef = "series"
# # identifier = "Ij5DqJREPW"
# # weight = 40

# [[main]]
# name = "Categorie"
# # pre = "folder"
# pageRef = "categories"
# identifier = "Ij5DqJRRIEF"
# weight = 50


[[footer]]
none = "none"

[[footer]]
# name = "LinkedIn"
url = "https://www.linkedin.com/company/qubito-student-team-politecnico-di-torino/"
pre = "linkedin"
identifier = "IjSDSJREPW"
weight = 1

# [[footer]]
# # name = "Twitter"
# url = "https://twitter.com/qubito_team"
# pre = "twitter"
# identifier = "aS3gqJREPW"
# weight = 2

# [[footer]]
# # name = "GitHub"
# url = ""    
# pre = "github"
# identifier = "Ig4sDJREPW"
# weight = 3

# [[footer]]
# # name = "YouTube"
# url = "https://www.youtube.com/@qubito"
# pre = "youtube"
# identifier = "Ij5RSDREPW"
# weight = 4

[[footer]]
# name = "Instagram"
url = "https://www.instagram.com/qubitoteam_polito/"
pre = "instagram"
identifier = "Ij5DqGDFCS"
weight = 5

# [[footer]]
# # name = "Telegram"
# url = "https://t.me/qubito_org"
# pre = "telegram"
# identifier = "Ij5AqEWRPW"
# weight = 6

# [[footer]]
# # name = "Discord"
# url = "https://discord.gg/4q2k7v3"
# pre = "discord"
# identifier = "Ij5DqJREPW"
# weight = 7