# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://blowfish.page/docs/getting-started/

theme = "blowfish" # UNCOMMENT THIS LINE
baseURL = "https://qubito.polito.it/"
defaultContentLanguage = "it"
defaultContentLanguageInSubdir = false


pluralizeListTitles = false # hugo function useful for non-english languages, find out more in  https://gohugo.io/getting-started/configuration/#pluralizelisttitles

enableRobotsTXT = true
summaryLength = 0

buildDrafts = false
buildFuture = false

enableEmoji = true

# googleAnalytics = "G-XXXXXXXXX"

[pagination]
  pagerSize = 100

[imaging]
  anchor = 'Center'

[sitemap]
  changefreq = 'daily'
  filename = 'sitemap.xml'
  priority = 0.5

[outputs]
  home = ["HTML", "RSS", "JSON"]

[related]
  threshold = 0
  toLower = false

    [[related.indices]]
        name = "tags"
        weight = 100

    [[related.indices]]
        name = "categories"
        weight = 100

    [[related.indices]]
        name = "series"
        weight = 50

    [[related.indices]]
        name = "authors"
        weight = 20

    [[related.indices]]
        name = "date"
        weight = 10

    [[related.indices]]
      applyFilter = false
      name = 'fragmentrefs'
      type = 'fragments'
      weight = 10

[languages]
[languages.it]
contentDir = "content"
languageName = "Italiano"
weight = 1
title = "QubiTO"
[languages.it.params]
displayName = "IT"
isoCode = "it"
rtl = false
dateFormat = "2 January 2006"
logo = "websiteLogo.svg"
secondaryLogo = "websiteLogo.svg"
description = "QubiTO è una comunità aperta a chiunque condivida la nostra passione per la scienza e la tecnologia quantistica. Che tu sia un fisico, un ingegnere, uno sviluppatore, un designer o semplicemente una mente curiosa, con noi troverai uno spazio dove le tue idee potranno evolversi. Facciamo ricerca, partecipiamo a hackathon e ci spingiamo oltre i confini dell’innovazione quantistica — insieme."
contentDir = "content"
mainSections = ["articles","team"]
copyright = "©2025 QubiTO. Tutti i diritti riservati."
creator = "Creato dalla Divisione Divulgazione di QubiTO"
githubEditText = "Modifica su GitHub"

[languages.it.taxonomies]
tag = "tags"
category = "categories"
author = "authors"
series = "series"

[languages.en] 
contentDir = "content"
languageName = "English"
weight = 2
title = "QubiTO"

[languages.en.params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
logo = "websiteLogo.svg"
secondaryLogo = "websiteLogo.svg"
description = "QubiTO is an open community for anyone who shares our passion for quantum science and technology. Whether you are a physicist, engineer, developer, designer, or simply a curious mind, you will find a space with us where your ideas can evolve. We conduct research, participate in hackathons, and push the boundaries of quantum innovation — together."
contentDir = "content"
mainSections = ["articles","team"]
copyright = "©2025 QubiTO. All rights reserved."
creator = "Created by QubiTO's Divulgation Division"
githubEditText = "Edit on GitHub"

[languages.en.taxonomies]
tag = "tags"
category = "categories"
author = "authors"
series = "series"

