name: Build and Deploy Hugo to qubito-pages

on:
  push:
    branches:
      - main
      - staging

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v3

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.124.1' # or your version

      - name: Init and update submodules
        run: git submodule update --init --recursive

      - name: Build site
        run: hugo --minify

      - name: Checkout target repo
        uses: actions/checkout@v3
        with:
          repository: org/qubito-pages
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          path: qubito-pages

      - name: Sync built files to target repo
        run: |
          DEST_BRANCH=${{ github.ref_name }}
          cd qubito-pages
          git switch $DEST_BRANCH || git switch -c $DEST_BRANCH origin/$DEST_BRANCH
          rm -rf ./*
          cp -r ../public/* ./
          touch .nojekyll
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add .
          git commit -m "Deploy from qubito-website:${DEST_BRANCH}" || echo "No changes"
          git push origin HEAD:$DEST_BRANCH
