name: Build and Deploy Hugo to qubito-pages

on:
  push:
    branches:
      - main
      - staging

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v3

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.124.0' # or your version

      - name: Init and update submodules
        run: git submodule update --init --recursive

      - name: Build site
        run: hugo --minify

      - name: Checkout gh-pages branch
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
          ref: gh-pages
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          path: gh-pages

      - name: Sync built files to gh-pages branch
        run: |
          cd gh-pages
          rm -rf ./*
          cp -r ../public/* ./
          touch .nojekyll
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add .
          git commit -m "Deploy from qubito-website:${{ github.ref_name }}" || echo "No changes"
          git push origin gh-pages
